repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: migrations/
        args:
          - --profile=black
          - --line-length=88
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.11.0
    hooks:
      - id: black
        exclude: migrations/
        args: [--line-length=88]
        language_version: python3.12
#  - repo: https://github.com/PyCQA/flake8
#    rev: 6.1.0
#    hooks:
#      - id: flake8
#        exclude: migrations/
#        args:
#          - --max-line-length=88
#          - --ignore=E131,E126,E402,E501,W503,E722
#  - repo: https://github.com/PyCQA/pylint
#    rev: "pylint-2.7.2"
#    hooks:
#      - id: pylint
#        exclude: "[a-zA-Z]*/(migrations)/(.)*"
#        args: [ "--load-plugins=pylint_django", "--django-settings-module=mysite.settings" ]
#        additional_dependencies: [
          # pylint dependency
#          django,
#          pylint_django,
#        ]
