# Generated by Django 5.2.1 on 2025-05-30 05:37

import app.utils
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="標題")),
                ("desc", models.TextField(blank=True, verbose_name="說明")),
                ("location", models.CharField(max_length=255, verbose_name="地點")),
                (
                    "salary_range",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        validators=[app.utils.salary_range_validator],
                        verbose_name="薪資範圍",
                    ),
                ),
                (
                    "salary_range_avg",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(28590)],
                        verbose_name="薪資範圍平均",
                    ),
                ),
                ("company_name", models.CharField(max_length=255, verbose_name="公司名稱")),
                (
                    "posting_date",
                    models.DateField(default=datetime.date.today, verbose_name="發布日期"),
                ),
                (
                    "expiration_date",
                    models.DateField(
                        default=datetime.date(2025, 6, 13), verbose_name="刊登期限"
                    ),
                ),
                (
                    "required_skills",
                    models.CharField(
                        blank=True,
                        help_text="逗號分隔的技能列表",
                        max_length=200,
                        verbose_name="必要技能",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("EXPIRED", "Expired"),
                            ("SCHEDULED", "Scheduled"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "工作職缺",
                "verbose_name_plural": "工作職缺",
                "ordering": ["-created_at"],
            },
        ),
    ]
